#+LATEX_HEADER: \usepackage{placeins}
#+TITLE: Assignment 2
#+SUBTITLE: CSC 520 Spring 2022 001
#+AUTHOR: Nathan Vercaemert
* Question 1
Execution instructions and solutions locations explained:
#+BEGIN_SRC shell
  ./Q1/README.pdf
#+END_SRC
* Question 2
Execution instructions and solutions locations explained:
#+BEGIN_SRC shell
  ./Q2/README.pdf
#+END_SRC
** Heuristic Explained
In navigating from A to B, where A and B are either (0, 0), a key, or the door (in that order), Manhattan distance is used as a heuristic.
*** Admissibility
Manhattan distance will never overestimate the distance that Harry must travel because the Manhattan distance is the shortest path that Harry can travel. Harry will only ever take this path if it is unobstructed.
*** Consistency
Similarly to [[*Admissibility][Admissibility]], the heuristic is consistent because the shortest path that Harry can take to an intermediate location (if unobstructed) is the Manhattan distance. If the intermediate location is on the path to the destination, then the total cost to/from the intermediate location will be equal to the direct cost to the destination. Otherwise, the total distance to/from the intermediate location will be greater than the direct cost to the destination. This is a property of euclidean space; our mazes are an abstraction of euclidean space.
** Paths Expanded
| Maze | DFS | BFS |
|------+-----+-----|
|    1 |  30 |  40 |
|    2 |     |     |
|    3 |  24 |  27 |
|    4 |     |     |
|    5 |  96 |  50 |
*** Comparison
With small mazes, DFS is able to find a solution with fewer paths. As the size of the maze increases, DFS runs the risk of searching more unsuccessful paths.

Ultimately, there is a relationship between the distance to the portal (from Harry) and the size of the maze. Because BFS expands incrementally, it will perform better than DFS when the portal is close to Harry and the maze is large (unless DFS "gets lucky" and the portal is located on a high priority path). As the size of the maze increases, the number of deep paths without a solution increases.
** Note
Keys are collected in the order in which they are closest to Harry based on A*. This process was determined by the instructors.
